# **Aplikasi KAL**

## **Page Rank**

PageRank (PR) adalah algoritma pencarian yang digunakan oleh Google Search untuk memberi peringkat halaman web, dalam mengukur seberapa pentingnya bagi pengguna di hasil mesin pencarian mereka

Menurut Google:

PageRank bekerja dengan menghitung jumlah dan kualitas tautan ke suatu halaman untuk menentukan perkiraan kasar seberapa penting situs web tersebut. Asumsi yang mendasarinya adalah bahwa situs web yang lebih penting cenderung menerima lebih banyak tautan dari situs web lainnya.

## **Konsep**

PageRank, memiliki konsep dasar yang sama dengan link popularity, tetapi tidak hanya memperhitungkan “jumlah” inbound dan outbound link. Pendekatan yang digunakan adalah sebuah halaman akan diangap penting jika halaman lain memiliki link ke halaman tersebut. Sebuah halaman juga akan menjadi semakin penting jika halaman lain yang memiliki rangking (pagerank) tinggi mengacu ke halaman tersebut.

Dengan pendekatan yang digunakan PageRank, proses terjadi secara rekursif dimana sebuah rangking akan ditentukan oleh rangking dari halaman web yang rangkingnya ditentukan oleh rangking halaman web lain yang memiliki link ke halaman tersebut. Proses ini berarti suatu proses yang berulang (rekursif). Di dunia maya, ada jutaan bahkan milyaran halaman web. Oleh karena itu sebuah rangking halaman web ditentukan dari struktur link dari keseluruhan halaman web yang ada di dunia maya. Sebuah proses yang sangat besar dan komplek.

## **Algoritma**

Dari pendekatan yang sudah dijelaskan pada artikel konsep pagerank, Lawrence Page and Sergey Brin membuat algoritma pagerank seperti di bawah:

Algoritma awal

$$
PR(A) = (1-d) + d \left( \frac{PR(T1)}{C(T1)} + \cdots + \frac{PR(Tn)}{C(Tn)} \right)
$$

Salah satu algoritma lain yang dipublikasikan

$$
PR(A) = \frac{(1-d)}{N} + d \left( \frac{PR(T1)}{C(T1)} + \cdots + \frac{PR(Tn)}{C(Tn)} \right)
$$

**PR(A)** adalah Pagerank halaman A

**PR(T1)** adalah Pagerank halaman T1 yang mengacu ke halaman A

**C(T1)** adalah jumlah link keluar (outbound link) pada halaman T1

**d** adalah damping factor yang bisa diberi antara 0 dan 1.

**N** adalah jumlah keseluruhan halaman web (yang terindeks oleh Google)

Dari algoritma di atas dapat dilihat bahwa pagerank ditentukan untuk setiap halaman anda bukan keseluruhan situs web. Pagerank sebuah halaman ditentukan dari pagerank halaman yang mengacu kepadanya yang juga menjalani proses penentuan pagerank dengan cara yang sama, jadi proses ini akan berulang sampai ditemukan hasil yang tepat.

Akan tetapi pagerank halaman A tidak langsung diberikan kepada halaman yang dituju, akan tetapi sebelumnya dibagi dengan jumlah link yang ada pada halaman T1 (outbound link), dan pagerank itu akan dibagi rata kepada setiap link yang ada pada halaman tersebut. Demikian juga dengan setiap halaman lain “Tn” yang mengacu ke halaman “A”.

Setelah semua pagerank yang didapat dari halaman-halaman lain yang mengacu ke halaman “A” dijumlahkan, nilai itu kemudian dikalikan dengan damping factor yang bernilai antara 0 sampai 1. Hal ini dilakukan agar tidak keseluruhan nilai pagerank halaman T didistribusikan ke halaman A.

## **Implentasi**

$$
A =
\begin{bmatrix}
0 & 0 & 1 & 1/2\\
1/3 & 0 & 0 & 0\\
1/3 & 1/2 & 0 & 1/2\\
1/3 & 1/2 & 0 & 0\\
\end{bmatrix}
$$

In [1]:
import numpy as np

A = np.array([
    [0, 0, 1, 1/2],
    [1/3, 0, 0, 0],
    [1/3, 1/2, 0, 1/2],
    [1/3, 1/2, 0, 0]
])

V = np.array([
    [0.25],
    [0.25],
    [0.25],
    [0.25]
])

toleransi = 1e-6

beda = np.inf
iteration = 0

while beda > toleransi:
    V_baru = np.dot(A, V)
    beda = np.linalg.norm(V_baru - V)
    V = V_baru
    iteration += 1
    print(f"V {iteration}:")
    print(f'{V}\n')

print("Hasil akhir:")
print(V)


V 1:
[[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]]

V 2:
[[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]

V 3:
[[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]]

V 4:
[[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]]

V 5:
[[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]]

V 6:
[[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]]

V 7:
[[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]]

V 8:
[[0.38671875]
 [0.12991898]
 [0.28978588]
 [0.19357639]]

V 9:
[[0.38657407]
 [0.12890625]
 [0.29065394]
 [0.19386574]]

V 10:
[[0.38758681]
 [0.12885802]
 [0.29024402]
 [0.19331115]]

V 11:
[[0.38689959]
 [0.1291956 ]
 [0.29028019]
 [0.19362461]]

V 12:
[[0.3870925 ]
 [0.12896653]
 [0.29037664]
 [0.19356433]]

V 13:
[[0.38715881]
 [0.12903083]
 [0.29029626]
 [0.1935141 ]]

V 14:
[[0.38705331]
 [0.12905294]
 [0.2903254 ]
 [0.19356835]]

V 15:
[[0.38710958]
 [0.12901777]
 [0.29032841]
 [0.19354424]]

V 16:
[[0.38710053]
 [0.12903653]
 [0.29031753]
 