# **Determinan Matriks**
Determinan matriks merupakan selisih antara perkalian elemen-elemen pada diagonal 1 dengan perkalian elemen-elemen pada diagonal 2. Determinan matriks harus memiliki ordo yang sama.

## **Sifat Matriks**
1. Matriks identitas nilai nya 1
2. Mengubah baris akan mengubah tanda determinan
3. Jika suatu baris kelipatan dari baris yang lain maka determinan matriks tersebut 0


In [8]:
import numpy as np

# Definisikan matriks
matrixA = np.array([[1, 0], [0, 1]])
matrixB = np.array([[1,0,0],[0,1,0],[0,0,1]])
matrixC = np.array([[1,2,1],[3,1,2],[2,1,2]])
matrixD = np.array([[3,1,2],[1,2,1],[2,1,2]])
matrixE = np.array([[1,2,1],[2,4,2],[2,1,2]])
matrixF = np.array([[1,2,1],[2,4,2],[2,4,3]])
matrixG = np.array([[6,2,4],[2,4,2],[4,2,4]])

# Hitung determinan
det1 = round(np.linalg.det(matrixA))
det2 = round(np.linalg.det(matrixB))
det3 = round(np.linalg.det(matrixC))
det4 = round(np.linalg.det(matrixD))
det5 = round(np.linalg.det(matrixE))
det6 = round(np.linalg.det(matrixF))
det7 = round(np.linalg.det(matrixG))

print(f'Determinannya adalah: {det1}')
print(f'Determinannya adalah: {det2}')
print(f'Determinannya adalah: {det3}')
print(f'Determinannya adalah: {det4}')
print(f'Determinannya adalah: {det5}')
print(f'Determinannya adalah: {det6}')
print(f'Determinannya adalah: {det7}')

Determinannya adalah: 1
Determinannya adalah: 1
Determinannya adalah: -3
Determinannya adalah: 3
Determinannya adalah: 0
Determinannya adalah: 0
Determinannya adalah: 24


4. Jika ada matriks 1 dan matriks 2 nya kelipatan 2 dari matriks 1 maka kelipatan suatu matriks dikali dengan ordo matiks dan dikali hasil determinan

In [9]:
import numpy as np
matrixA = np.array([[3, 4], [2, 1]])
matrixH = np.array([[6, 8], [4, 2]])

det1 = round(np.linalg.det(matrixA))
det2 = round(np.linalg.det(matrixH))

print(f'Determinannya adalah: {det1}')
print(f'Determinannya adalah: {det2}')


Determinannya adalah: -5
Determinannya adalah: -20


5. Jika salah satu baris matriks dikali 2 maka hasil determinannya sama dengan dikali 2 dan seterusnya berkelipatan

In [10]:
import numpy as np
matrixA = np.array([[3, 4], [2, 1]])
matrixI = np.array([[6, 8], [2, 1]])

det1 = round(np.linalg.det(matrixA))
det2 = round(np.linalg.det(matrixI))

print(f'Determinannya adalah: {det1}')
print(f'Determinannya adalah: {det2}')


Determinannya adalah: -5
Determinannya adalah: -10


6. Sama dengan no.7 jika salah satu kolom matriks dikali 2 maka hasil determinannya sama dengan dikali 2 dan seterusnya berkelipatan

In [11]:
import numpy as np
matrixA = np.array([[3, 4], [2, 1]])
matrixJ = np.array([[6, 4], [4, 1]])

det1 = round(np.linalg.det(matrixA))
det2 = round(np.linalg.det(matrixJ))

print(f'Determinannya adalah: {det1}')
print(f'Determinannya adalah: {det2}')



Determinannya adalah: -5
Determinannya adalah: -10


7. Determinan segitiga atas dan bawah

In [12]:
import numpy as np
matrix1 = np.array([[1,2,1],[0,1,3],[0,0,1]])
matrix2 = np.array([[1,0,0],[3,1,0],[2,1,2]])

det1 = round(np.linalg.det(matrix1))
det2 = round(np.linalg.det(matrix2))

print(f'Determinan SEGITIGA BAWAH adalah: {det1}')
print(f'Determinan SEGITIGA ATAS adalah: {det2}')


Determinan SEGITIGA BAWAH adalah: 1
Determinan SEGITIGA ATAS adalah: 2


8. Perkalian determinan 2 matriks

In [13]:
import numpy as np
matrix1 = np.array([[2, 1], [1, 1]])
matrix2 = np.array([[1, 1], [1, 1]])

det1 = round(np.linalg.det(matrix1))
det2 = round(np.linalg.det(matrix2))

print(f'Determinannya adalah: {det1}')
print(f'Determinannya adalah: {det2}')

#hasil perkalian matriks1 dan 2, dan mencari determinannya
matrixC= np.array([[3,3],[2,2]])
det3 = round(np.linalg.det(matrixC))
hasil=det1 * det2
print(f'Determinannya adalah: {det3}')
print(f'hasil perkalian: {hasil}')

Determinannya adalah: 1
Determinannya adalah: 0
Determinannya adalah: 0
hasil perkalian: 0


## **Menghitung determinan matriks dan invers matrik matriks 5x5**

In [14]:
import numpy as np

# Membuat matriks 5x5
matrix = np.array([
    [2, 3, 1, 1, 4],
    [1, 2, 2, 3, 1],
    [1, 2, 3, 4, 1],
    [1, 1, 1, 2, 2],
    [1, 3, 2, 1, 4]
])

# Menampilkan matriks
print("Matriks:")
print(matrix)

# Menghitung determinan matriks
determinant = np.linalg.det(matrix)
print("\nDeterminan Matriks:")
print(determinant)

# Menghitung invers matriks
if determinant != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInvers Matriks:")
    print(inverse_matrix)
else:
    print("\nMatriks ini tidak memiliki invers karena determinannya adalah 0.")

Matriks:
[[2 3 1 1 4]
 [1 2 2 3 1]
 [1 2 3 4 1]
 [1 1 1 2 2]
 [1 3 2 1 4]]

Determinan Matriks:
5.999999999999997

Invers Matriks:
[[ 1.66666667 -2.5         2.16666667 -0.83333333 -1.16666667]
 [-0.33333333  2.         -1.33333333 -0.33333333  0.33333333]
 [ 0.66666667 -2.5         2.16666667 -0.83333333 -0.16666667]
 [-0.66666667  1.5        -1.16666667  0.83333333  0.16666667]
 [-0.33333333  0.         -0.33333333  0.66666667  0.33333333]]
