## Aljabar Matrik
(Tidak Mengerjakan tidak boleh masuk)


*   apa itu matrik
*   apa itu operasi matrik
*   penjumlahan, perkalian, pengurangan, transpose matrik
*   Buat program untuk mengalikan matrik A dan B



disuruh membuat matrix a = 3x3, b = 3x3, c = 3x2, dan d = 3x3

mxn matrix A dan nxk matrix C

In [6]:
import numpy as np
import sympy as sy

In [7]:
A = np.array ([[2,4,-1],[3,4,1],[3,0,1]])
B = np.array ([[2,1,3],[-2,3,1],[3,1,2]])
C = np.array ([[3,0],[2,4],[2,1]])
D = np.array ([[1,1,3],[-2,0,1],[1,1,1]])
print(A)
print('='* 90)
print(B)
print('='* 90)
print(C)
print('='* 90)
print(D)

[[ 2  4 -1]
 [ 3  4  1]
 [ 3  0  1]]
[[ 2  1  3]
 [-2  3  1]
 [ 3  1  2]]
[[3 0]
 [2 4]
 [2 1]]
[[ 1  1  3]
 [-2  0  1]
 [ 1  1  1]]


In [18]:
print("melakukan perkalian matrix")
print(A@B)
print("\nmelakukan penjumlahan matrix")
print(A+B)
print("\nmelakukan penjumlahan matrix")
E = A+B
print(E)
print("\nmelakukan perkalian skalar matrix")
F = 2*A
print(F)
print("\nmelakukan perkalian matrix")
G = A@C
print(G)
print()
#A(BC)= (AB)C
H=B@C
I=A@H
print()
K=A@B
O=K@C
print(I)
print()
print(O)

melakukan perkalian matrix
[[-7 13  8]
 [ 1 16 15]
 [ 9  4 11]]

melakukan penjumlahan matrix
[[4 5 2]
 [1 7 2]
 [6 1 3]]

melakukan penjumlahan matrix
[[4 5 2]
 [1 7 2]
 [6 1 3]]

melakukan perkalian skalar matrix
[[ 4  8 -2]
 [ 6  8  2]
 [ 6  0  2]]

melakukan perkalian matrix
[[12 15]
 [19 17]
 [11  1]]


[[21 60]
 [65 79]
 [57 27]]

[[21 60]
 [65 79]
 [57 27]]


In [20]:
Ctrans=C.transpose()
print(C)
print()
print(Ctrans)

[[3 0]
 [2 4]
 [2 1]]

[[3 2 2]
 [0 4 1]]


In [1]:
import numpy as np

# Matriks 3x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Matriks 3x2
B = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Inisialisasi matriks hasil dengan ukuran 3x2 dengan nilai nol
result = np.zeros((3, 2))

# Perulangan untuk mengalikan matriks A dan B
for i in range(3):  # Loop untuk baris matriks A
    for j in range(2):  # Loop untuk kolom matriks B
        for k in range(3):  # Loop untuk jumlah kolom matriks A (atau baris matriks B)
            result[i][j] += A[i][k] * B[k][j]

# Cetak hasil
print("Hasil perkalian matriks A dan B:")
print(result)

Hasil perkalian matriks A dan B:
[[ 22.  28.]
 [ 49.  64.]
 [ 76. 100.]]
